### PR TITLE
Added some docblocks and support for string-based file loading and saving.

### PR DESCRIPTION
**Pull request by Sjaakmoes**

### CODE REVIEW

**Comment by adityapatadia** [comment]
Hey, I see huge gitignore file. Please do something about it. Apart from that, it would be great if you can also update readme.

**Comment by Sjaakmoes** [comment]
Done!

**Comment by adityapatadia** [comment]
Can you please check the current code. I recently merged another branch and it is conflicting.

**Comment by Sjaakmoes** [comment]
Merged it, should be good now.

**Comment by olegpopadko** [comment]
Why toString not magic method __toString?

**Comment by adityapatadia** [comment]
@Sjaakmoes going to implement __toString?

**Comment by adityapatadia** [comment]
Everything looks fine. I am merging it. Send new PR if you implement __toString.

**Pull request merged**
