### PR TITLE
Compression vs quality

### PR DESCRIPTION
**Pull request by verschoof**
A little bit explanation about my change.

In this PR I introduce a new parameter (compression) because there are now 2 concepts in 1 variable. (at the last and optional, so no BC break)

JPEG quality and the PNG quality (read docs: Compression level).
In this library the quality is used for both options, but JPEG expect 0-100 and PNG 0-9. So I separated them :).

### CODE REVIEW

**Comment by adityapatadia** [comment]
This will actually be BC break. If some people actually used quality for PNG image, they would no longer get their desired quality output. Can we find some better way?

**Comment by verschoof** [comment]
True, but now you have a bug. You cannot solve the bug without a BC break. Maybe tag new major version? :) (my first comment that there is no BC Break is indeed wrong :( )

**Comment by adityapatadia** [comment]
It would be a too big BC break. There might be people who would be using quality parameter for PNG. I would not say it a bug but an odd API. Users have ```quality_jpg``` and ```quality_png``` params also to change this. I am closing this PR for now as tagging a new major version for this is not appropriate at this point.

**Comment by verschoof** [comment]
Well, I do not agree with the "too big BC break". You have to go on with improving your code.
So *if* this improves your lib go merge it and tag it to 2.0.0. All those people at 1.* has to check the change log and fix something before going to 2.

Nothing to be afraid of. 👍

**Pull request closed without merging**
