### PR TITLE
Fix testing issue in newer version of PHPUnit

### PR DESCRIPTION
**Pull request by cainmi**
where expected error was not caught

### CODE REVIEW

**Comment by adityapatadia** [comment]
Thanks, can you also take a took at #12 ?

**Comment by cainmi** [comment]
If you merge this, #12 and #14 can rebase against it and should pass.

**Comment by adityapatadia** [comment]
Can you please check #12 is fine to merge? The changes?

**Comment by cainmi** [comment]
Please see comments on #12.

**Pull request merged**
