### PR TITLE
Adding crop positions and documentation blocks

### PR DESCRIPTION
**Pull request by hugoseabra**

### CODE REVIEW

**Comment by adityapatadia** [comment]
Travis build failed. Please check this commit. Also change the name in composer.json.

**Comment by hugoseabra** [comment]
Done.

Do I have to resend the request?

**Comment by adityapatadia** [comment]
Your changes are not visible here. May be u want to resend.

**Comment by olegpopadko** [comment]
Did you push your master?

**Comment by adityapatadia** [comment]
Yeah the changes are still not visible in your master. Please push.

**Comment by hugoseabra** [comment]
Hey @adityapatadia,

I just can't send another pull request. My master branch is exactly like it is meant to be, but the request has failed because you unit tests has failed. Did you see the details of the failure?

I added a crop position support in your ImageResize class and organized the docblocks to let things fine for documentation. Maybe if you clone my forked repository, you can get all the few changes I've done.

Best regards,

**Comment by adityapatadia** [comment]
Your master branch does not have the changes I suggested. For example, name of package still has your name in composer.json as found here. https://github.com/hugoseabra/php-image-resize/blob/master/composer.json Apart from that, the travis build failed and the error is given here:https://travis-ci.org/eventviva/php-image-resize/jobs/46809388 please check it and make appropriate commits in your master branch. They will automatically appear here.

**Comment by cainmi** [comment]
The test failure is weird, because none of that code has changed.
Might be because of changes in an updated version of PHPUnit.
I'll look into it shortly.

**Comment by adityapatadia** [comment]
OK, let me know when you are done with it.

**Comment by cainmi** [comment]
This should be fine to merge... the issue has been fixed upstream.
If you want to see the tests pass though this PR will have to be rebased with the changes in #13.

**Comment by cainmi** [comment]
Or maybe hit [Restart Build](http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit).

**Comment by cainmi** [comment]
Although I wouldn't merge this just yet, the composer.json name param is still wrong.

**Comment by adityapatadia** [comment]
@hugoseabra can you fix the name in composer?

**Comment by hugoseabra** [comment]
Done.

**Comment by cainmi** [comment]
Looks like the test are passing now, but there isn't any coverage for the new functionality.

**Comment by adityapatadia** [comment]
Let me know if someone can write a test for the same.

**Comment by cainmi** [comment]
Maybe merge first, as I can't push to this PR.

**Comment by adityapatadia** [comment]
Ok closing. I won't tag new version until tests are covering this functionality.

**Pull request merged**
