### PR TITLE
Add image filters

### PR DESCRIPTION
**Pull request by mikestreety**

### CODE REVIEW

**Comment by mikestreety** [comment]
As mention in [this issue](https://github.com/eventviva/php-image-resize/issues/89) I've added grayscale and other image filters

**Comment by adityapatadia** [comment]
Checks are failing. Can you look what is wrong? Please also write unit test for new functions.

**Comment by mikestreety** [comment]
Apologies - was using PHP7 at home.

I'm not quite sure where to begin with the tests. Would I create images in the ressources and compare them?

**Comment by adityapatadia** [comment]
check here: https://github.com/eventviva/php-image-resize/tree/master/test

**Comment by adityapatadia** [comment]
Hi, Any update on this? Will you correct it?

**Comment by mikestreety** [comment]
No, sorry. I had a look and don't understand what I need to do.

**Comment by adityapatadia** [comment]
Please check link for unit tests already written. You would ideally add one pre-processed image as string and then compare it with one unprocessed image processed by this library. This file has all tests written: https://github.com/eventviva/php-image-resize/blob/master/test/Test.php

**Comment by rakshazi** [comment]
Hi!
Any update on this?

**Comment by adityapatadia** [comment]
Did you make unit test changes? Sorry I did not check whether you did.

**Comment by mikestreety** [comment]
Hello,

Sorry, I've not looked further into this - been slammed with work and personal projects.

I'm not quite sure how to make a pre-processed image as a string and still unsure how to write the tests for this. Any help would be hugely appreciated.

**Comment by adityapatadia** [comment]
You can use ```fromstring``` and ```tostring``` methods of this library. Please check readme file and also check the test source code which can be found from above link I posted.

**Comment by mikestreety** [comment]
Hey, sorry for the delayed reply. I've tried and failed many times to pick this up and understand it but my brain just won't accept it.

If this is not a viable pull request - delete it and I'll use my own fork on my personal projects. Sorry to be a burden! 

Thanks for the great package 😄

**Comment by nanmu42** [comment]
Thanks for the effort anyway, dude. 👍

**Pull request closed without merging**
