### PR TITLE
Add watermark support

### PR DESCRIPTION
**Pull request by villeristi**
As requested in #64.

### CODE REVIEW

**Comment by adityapatadia** [comment]
I don't see a unit test written for it. Can you please also add it so we ensure a bug free implementation?

**Comment by villeristi** [comment]
@adityapatadia added =>

**Comment by adityapatadia** [comment]
Sorry to ask you again but the test should ideally compare output by library with a reference test image. You can create watermarked image and then compare the image output by this library to the reference image. I know, some unit tests of library are not as rigorous but I will repair them when I get free. 

Meanwhile, when we are adding new test I would like them to be good.

**Comment by villeristi** [comment]
Ah, my bad. I thought you were just asking basic `exists`, `doesn'tThrowAnyErrors` -test. I'll add them when able =>

**Comment by adityapatadia** [comment]
Can you fix the failing checks? I would marge after checks pass.

**Comment by villeristi** [comment]
Apparently there's something going on with travis as these passed locally. Have to dig into

**Comment by adityapatadia** [comment]
Hi, Can you resolve the issues?

**Comment by villeristi** [comment]
Hi, I'm ont sure if I can alter the Travis-configuration. It passes on local though.

**Comment by adityapatadia** [comment]
It's not travis config issue. The images are not matching.

**Comment by adityapatadia** [comment]
Any update on this?

**Pull request closed without merging**
