### PR TITLE
WebP image support

### PR DESCRIPTION
**Pull request by rakshazi**
Replacing #85 
PS: My editor automatically fixed codestyle (PSR-1/PSR-2), sorry :(

### CODE REVIEW

**Comment by rakshazi** [comment]
@adityapatadia please, review build log: https://travis-ci.org/eventviva/php-image-resize/jobs/271964089#L449 some problems on Travis CI side?

**Comment by adityapatadia** [comment]
Seems like their error. Can you try again after some time?

**Comment by rakshazi** [comment]
Same problem on master branch: https://travis-ci.org/eventviva/php-image-resize/jobs/271458267
I will try later today

**Comment by rakshazi** [comment]
@adityapatadia seems that 5.3 is not supported by Travis default environment anymore: https://github.com/travis-ci/travis-ci/issues/2963
Can you merge this PR, please?

**Comment by adityapatadia** [comment]
I dropped 5.3 from tests and they are passing now.

**Pull request merged**
