### PR TITLE
Needed to crop between the center and the top.

### PR DESCRIPTION
**Pull request by Pastou**
I added this constant to have the possibility to use the crop function and crop it between the top and the center.

### CODE REVIEW

**Comment by adityapatadia** [comment]
Can you update readme file about the same?

**Comment by Pastou** [comment]
Hi Aditya,

Could you specify which README you're talking about ?

Is it the README on the master branch or are you talking about the API 
doc - source-class-Eventviva.ImageResize.html - in the gh-pages branch ?

Best,

Alexis

**Comment by adityapatadia** [comment]
Not the doc. I am talking about README.md. The doc will me automatically updated based on annotations of PHP.

**Comment by Pastou** [comment]
I updated the README.md let me know if that suits you ?

**Comment by adityapatadia** [comment]
Sorry for this but I mean you should provide proper example about what crop modes are available and give one example about how should it be used. 

When we write code, the API is obvious for us but not for users.

**Comment by adityapatadia** [comment]
Sorry for this but I mean you should provide proper example about what crop modes are available and give one example about how should it be used. 

When we write code, the API is obvious for us but not for users.

**Comment by Pastou** [comment]
@adityapatadia I have updated the documentation could you let me know if it's fine clear enough ?

**Pull request merged**
