### PR TITLE
Renamed toString() to get(), implemented __toString()

### PR DESCRIPTION
**Pull request by Sjaakmoes**
Get is a more appropriate name given that the function takes parameters which influence the resulting image (quality and image type). Also implemented the __toString() magic method.

### CODE REVIEW

**Comment by adityapatadia** [comment]
Seems good.

**Comment by adityapatadia** [comment]
Can you confirm that the entire library is covered by unit tests? If not, can you do it if you are working on this?

**Comment by Sjaakmoes** [comment]
The getCropPosition function isn't fully covered, i'll add a test for that in a bit.

**Comment by adityapatadia** [comment]
Ok, great :)

**Pull request merged**
